# Dockerfile.nginx
FROM nginx:alpine

# Удаляем дефолтную конфигурацию
RUN rm /etc/nginx/conf.d/default.conf

# Копируем нашу конфигурацию
COPY nginx.conf /etc/nginx/nginx.conf

# Статика будет смонтирована через volumes
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]