# Generated by Django 6.0.2 on 2026-03-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instruments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("entry_date", models.DateField(verbose_name="Дата ввода")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                ("is_new", models.BooleanField(default=True)),
                (
                    "image1",
                    models.ImageField(
                        upload_to="instruments/foto", verbose_name="Фото инструмента1"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        upload_to="instruments/foto", verbose_name="Фото инструмента2"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        upload_to="instruments/foto", verbose_name="Фото инструмента3"
                    ),
                ),
                (
                    "comment",
                    models.CharField(max_length=200, verbose_name="Комментарий"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_USE", "в работе"),
                            ("REPAIRED", "в ремонте"),
                            ("RELOCATED", "перемещен"),
                            ("BROKEN", "сломан"),
                        ],
                        default="IN_USE",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relocator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repairers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="Контактное лицо"),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Relocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relocations",
                        to="core.instruments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repairs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("failure_date", models.DateField()),
                (
                    "date_of_delivery_for_repair",
                    models.DateField(verbose_name="Дата сдачи в ремонт"),
                ),
                (
                    "date_of_receipt_from_repair",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приёма из ремонта"
                    ),
                ),
                (
                    "repair_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость ремонта",
                    ),
                ),
                (
                    "comment",
                    models.CharField(max_length=200, verbose_name="Комментарий"),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repairs",
                        to="core.instruments",
                        verbose_name="инструмент",
                    ),
                ),
                (
                    "repairer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repair_done",
                        to="core.repairers",
                        verbose_name="исполнитель",
                    ),
                ),
            ],
        ),
    ]
