# Generated by Django 6.0.2 on 2026-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_relocation_relocations_repairers_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruments",
            name="inventory_number",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Инвентарный номер"
            ),
        ),
    ]
