# Generated by Django 6.0.2 on 2026-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_instruments_inventory_n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relocations",
            name="comment",
            field=models.TextField(),
        ),
    ]
