# Generated by Django 6.0.2 on 2026-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_relocations_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruments",
            name="inventory_number",
            field=models.IntegerField(
                null=True, unique=True, verbose_name="Инвентарный номер"
            ),
        ),
    ]
