# Generated by Django 6.0.2 on 2026-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_instruments_inventory_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruments",
            name="inventory_number",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Инвентарный номер"
            ),
        ),
        migrations.AlterField(
            model_name="instruments",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_USE", "в работе"),
                    ("IN_REPAIR", "в ремонте"),
                    ("RELOCATED", "перемещен"),
                    ("BROKEN", "сломан"),
                ],
                default="IN_USE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="repairs",
            name="repair_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Стоимость ремонта",
            ),
        ),
    ]
