# Generated by Django 6.0.3 on 2026-03-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_instruments_options_alter_repairs_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruments",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="relocations",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="repairers",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="repairs",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
