# Generated by Django 6.0.3 on 2026-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_repairers_company_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruments",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="repairers",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="repairs",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
