# Generated by Django 6.0.3 on 2026-05-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_instruments_external_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relocators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ФИО")),
            ],
            options={
                "verbose_name": "Ответственный за перемещение",
                "verbose_name_plural": "Ответственные за перемещение",
            },
        ),
        migrations.DeleteModel(
            name="Relocator",
        ),
        migrations.AlterModelOptions(
            name="relocations",
            options={
                "ordering": ["-date"],
                "verbose_name": "Перемещение",
                "verbose_name_plural": "Перемещения",
            },
        ),
        migrations.AlterModelOptions(
            name="repairs",
            options={
                "ordering": ["-date_of_delivery_for_repair"],
                "verbose_name": "Ремонт",
                "verbose_name_plural": "Ремонты",
            },
        ),
        migrations.AddField(
            model_name="relocations",
            name="relocation_place",
            field=models.CharField(
                default="", max_length=200, verbose_name="Куда перемещен"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="relocations",
            name="comment",
            field=models.TextField(verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="relocations",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата перемещения"),
        ),
        migrations.AlterField(
            model_name="relocations",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relocations",
                to="core.instruments",
                verbose_name="Инструмент",
            ),
        ),
        migrations.AlterField(
            model_name="repairers",
            name="comment",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="repairers",
            name="company_details",
            field=models.JSONField(blank=True, default=dict, verbose_name="Реквизиты"),
        ),
        migrations.AlterField(
            model_name="repairs",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repairs",
                to="core.instruments",
                verbose_name="инструмент",
            ),
        ),
        migrations.AlterField(
            model_name="repairs",
            name="repairer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repair_done",
                to="core.repairers",
                verbose_name="исполнитель",
            ),
        ),
        migrations.AddIndex(
            model_name="instruments",
            index=models.Index(fields=["status"], name="core_instru_status_62fa65_idx"),
        ),
        migrations.AddIndex(
            model_name="instruments",
            index=models.Index(
                fields=["inventory_number"], name="core_instru_invento_f12967_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instruments",
            index=models.Index(fields=["name"], name="core_instru_name_6a6447_idx"),
        ),
        migrations.AddIndex(
            model_name="repairs",
            index=models.Index(
                fields=["instrument", "date_of_receipt_from_repair"],
                name="core_repair_instrum_e307b5_idx",
            ),
        ),
        migrations.AddField(
            model_name="relocations",
            name="relocator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relocations",
                to="core.relocators",
                verbose_name="Ответственный за перемещение",
            ),
        ),
    ]
